# Generated by Django 5.2 on 2025-04-28 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'verbose_name': 'Inscripción', 'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='curso',
            name='cupo_maximo',
            field=models.PositiveIntegerField(help_text='Número máximo de estudiantes permitidos'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='formador',
            field=models.ForeignKey(limit_choices_to={'rol': 'formador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_impartidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='curso',
            name='horario',
            field=models.CharField(help_text='Ejemplo: Lunes y Miércoles, 4:00 PM - 6:00 PM', max_length=100),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='asistencia',
            field=models.JSONField(default=list, help_text="Lista de fechas de asistencia (formato: ['YYYY-MM-DD', ...])"),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='calificacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calificación final del estudiante (ejemplo: 4.5)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscritos', to='core.curso'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'rol': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('formador', 'Formador'), ('estudiante', 'Estudiante')], default='estudiante', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
